name: pokedex
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_riverpod: ^2.5.3
  cached_network_image: ^3.4.0
  palette_generator: ^0.3.3+4
  screenshot: ^2.5.0
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner.png
    - assets/pokemon.json
    - assets/pokemon_sprites.json

  fonts:
    - family: Pokemon
      fonts:
        - asset: assets/fonts/Pokemon.ttf